server:
  port: ${running.port:8081}
  shutdown: graceful
  servlet:
    encoding:
      charset: utf-8
      force-response: true

spring:
  profiles:
    active: ${running.profile:local}
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://db-postgres-secmsa-core.cfgq2mm0w8uf.ap-northeast-2.rds.amazonaws.com:5432/postgres
#    username: postgres
#    password: asdfg12345
  #멀티 DB 설정
  # primary db
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://db-postgres-secmsa-core.cfgq2mm0w8uf.ap-northeast-2.rds.amazonaws.com:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: asdfg12345
  # secondary db - 그냥 이전에 사용 했던 DB로 일단 설정하자..
    secondary:
      #금융서버
      #jdbc-url: jdbc:postgresql://10.250.140.97:5432/postgres 
      jdbc-url: jdbc:postgresql://db-postgres-secmsa-core.cfgq2mm0w8uf.ap-northeast-2.rds.amazonaws.com:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: asdfg12345
      #금융서버 비밀번호
      #password: 1q2w3e4r

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
#  kafka:
#    name: stockcore
#    producer:
#      bootstrap-servers: inno3t2:4192
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      bootstrap-servers: inno3t2:4192
#      group-id: stockcore
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  messages:
    basename: messages/messages #message.properties 경로  messages 폴더 밑으로 모아 놓음
    encoding: utf-8
    cache-duration: 600 #600초 10분 마다 설정 파일 리로딩.

#카프카 구현 하면 추가하자..
#kafka:
#  send:
#    topic: sampleCChanged
#    group_id: msa3
#  rev:
#    topic: sampleAChanged
#    group_id: msa3

stockcore:
  swagger:
    enabled: true
  auth:
    token: #인증 토큰 정보
      secret: ZmluYW5jZS1tc2EtYmFja2VuZC1qd3Qtc2VjcmV0LWZpbmFuY2UtbXNhLWJhY2tlbmQtand0LXNlY3JldC1maW5hbmNlLW1zYS1iYWNrZW5kLWp3dC1zZWNyZXQK
      valid-minute: 30 #30분

#developers.kakao.com  
kako:
  native: 7867fd79c0f8c05701de0156d1cf9ac0
  restapi: 207f20eef7f66d7f8f212ce5a75c7606
  javascript: 0c1594a9d8e8668994f2b6f5711f4882
  adminkey: 69cbf5b366243c0780359e059791bc58