server:
  port: ${running.port:8081}
  shutdown: graceful
  servlet:
    encoding:
      charset: utf-8
      force-response: true

spring:
  profiles:
    active: ${running.profile:local}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    hibernate.ddl-auto: none
  primary:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      #jdbc-url: jdbc:mariadb://inno3t2:4121/my_db?useUnicode=true&serverTimezone=Asia/Seoul # 회사에서 테스트용
      jdbc-url: jdbc:mariadb://localhost:3306/customer?useUnicode=true&serverTimezone=Asia/Seoul # 집 로컬 docker 에서 테스트용
      username: root
      password: root
  secondary:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      #jdbc-url: jdbc:mariadb://inno3t2:4121/samplea?useUnicode=true&serverTimezone=Asia/Seoul # 회사에서 테스트용
      jdbc-url: jdbc:mariadb://localhost:3306/account?useUnicode=true&serverTimezone=Asia/Seoul # 집 로컬 docker 에서 테스트용
      username: root
      password: root
  kafka:
    name: sampleAChanged
    producer:
      bootstrap-servers: inno3t2:4192
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: inno3t2:4192
      group-id: msa3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  messages:
    basename: messages/messages #message.properties 경로  messages 폴더 밑으로 모아 놓음
    encoding: utf-8
    cache-duration: 600 #600초 10분 마다 설정 파일 리로딩.

kafka:
  send:
    topic: sampleCChanged
    group_id: msa3
  rev:
    topic: sampleAChanged
    group_id: msa3

msa3:
  swagger:
    enabled: true
  auth:
    token: #인증 토큰 정보
      secret: "TOKEN_SECURITY_KEY_가나다라마바사아자차카타파하" # 키문자열 또는 키파일 경로 너무 짧게 적으면 오류남.
      valid-minute: 30 #30분


